# Site settings
title: QMTECH XC7Z020 Notes
description: Notes on the QMTECH ZYNQ XC7Z020 starter kit
baseurl: /qmtech-xc7z020-notes
url: https://pavel-demin.github.io

release-image: https://github.com/pavel-demin/qmtech-xc7z020-notes/releases/download/20240811/qmtech-xc7z020-alpine-3.20-armv7-20240811.zip

adc-board-release: https://github.com/pavel-demin/qmtech-adc/releases/download/20240614/qmtech-adc-20240614.zip

sdr-smem-file: https://github.com/pavel-demin/sdr-smem/releases/download/20240204/sdr-smem-20240204.zip

# Build settings
markdown: kramdown
highlighter: rouge
